### ISSUE TITLE
专辑信息接口报错

### ISSUE THREAD

**Issue by Ericwyn** [jsososo/MiguMusicApi#18]
访问专辑信息接口 /album?id=1003767159 的时候， 报错如下

```
        name: cherrioFun(o).text()
              ^
TypeError: cherrioFun is not a function
    at Node.<anonymous> (D:\Chaos\web\MiguMusicApi\routes\album.ts:28:15)
    at initialize.each (D:\Chaos\web\MiguMusicApi\node_modules\cheerio\lib\api\traversing.js:553:26)
    at Object.<anonymous> (D:\Chaos\web\MiguMusicApi\routes\album.ts:25:25)
    at step (D:\Chaos\web\MiguMusicApi\routes\album.ts:32:23)
    at Object.next (D:\Chaos\web\MiguMusicApi\routes\album.ts:13:53)
    at fulfilled (D:\Chaos\web\MiguMusicApi\routes\album.ts:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jsososo** [comment]
我没找到这段报错的位置。。但是我现在用你的参数运行时ok的，是最新的master分支嘛

**Comment by Ericwyn** [comment]
是, 最新 master 分支
我这边看起来显示 cheerio 解析 html 的时候出错了
如果你那边可以正常运行的话, 可能是我这边运行环境的问题
