### ISSUE TITLE
使用forever启动报错

### ISSUE THREAD

**Issue by lcnwys** [jsososo/MiguMusicApi#6]
import createError = require('http-errors');
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error: Forever detected script exited with code: 1

网易云项目可以使用forever启动，但是migu的不行，我看migu是app.ts，我在全局安装ts-node的时候报错无法安装，是不是这个原因，我已经先安装了 typescript 但是一直提示我 `-- UNMET PEER DEPENDENCY typescript@>=2.7

npm WARN ts-node@8.10.2 requires a peer of typescript@>=2.7 but none was installed.
没安装上ts-node，在网上也找不到解决办法，大神知道怎么解决么

**Comment by jsososo** [comment]
ts-node 没安装成功嘛，安装的 typescript 是哪个版本的，会不会版本太低什么的，看报错时说没有高于2.7版本的 ts

**Comment by lcnwys** [comment]
我用npm全局安装的typescript 显示版本3.5

**Comment by jsososo** [comment]
再全局安装一下 tslint 试试呢

**Comment by lcnwys** [comment]
也是提示没有typescript 我卸载了typescript重新安装也还是不行，我查了库都有，好奇怪
![C11E8B64-FFE0-4415-BF90-694ECDEF123C](https://user-images.githubusercontent.com/40192017/84639305-c5308500-af2a-11ea-8d12-3b2e1e0db337.jpeg)

**Comment by jsososo** [comment]
tsc -v 都是正常的咯？我也不太清楚具体是为什么了，因为我也没怎么写过 ts 其实，还有一个 js 分支的，但是可能有些地方比较落后了，我也懒得同步更新了。。

**Comment by lcnwys** [comment]
找到一个解决办法 
forever start -c "npm start" app.ts 居然可以

**Comment by jsososo** [comment]
emmm，所以是启动器的关系？我倒是没用过 forever 一直都是用pm2

**Comment by lcnwys** [comment]
> emmm，所以是启动器的关系？我倒是没用过 forever 一直都是用pm2

我今天也改用 pm2 start npm --name test -- start 这样用npm启动就没问题啦

**Comment by lcnwys** [comment]
我很想知道为什么搜索Mijito查不到，却蹦出来迷迭香

**Comment by jsososo** [comment]
这个我是用的移动web端的接口，我访问了一下，他们确实搜不出来的。主要是pc上服务端渲染，没有借口，最多只能爬虫
